name: Build Android

on:
  workflow_dispatch:
    inputs:
      zip_url:
        description: "URL to the .zip file (from GCS or GitHub)"
        required: true
      webhook_url:
        description: "Optional webhook to notify"
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repo (required for Actions context)
        uses: actions/checkout@v4

      - name: Install required tools
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip openjdk-17-jdk

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Download ZIP from URL
        run: |
          echo "Downloading ZIP from ${{ github.event.inputs.zip_url }}"
          curl -L -o app.zip "${{ github.event.inputs.zip_url }}"
          unzip -q app.zip -d appdir

      - name: Detect gradlew location
        id: gradle-dir
        run: |
          dir=$(find appdir -type f -name 'gradlew' -exec dirname {} \; | head -n 1)
          echo "Detected gradle directory: $dir"
          echo "gradle_dir=$dir" >> "$GITHUB_OUTPUT"

      - name: List contents
        run: ls -R appdir

      - name: Build Android project
        working-directory: ${{ steps.gradle-dir.outputs.gradle_dir }}
        run: |
          sed -i 's/4<com.google.android.material.button.MaterialButton/<com.google.android.material.button.MaterialButton/' app/src/main/res/layout-sw447dp/activity_program_calc.xml
          sed -i 's|<string name="secondmodetext"\([^>]*\)>2nd</string>|<string name="secondmodetext"\1 translatable="false">2nd</string>|' app/src/main/res/values/strings.xml
          sed -i 's|<string name="text_res">textres</string>|<string name="text_res" translatable="false">textres</string>|' app/src/main/res/values/strings.xml
          chmod +x ./gradlew
          ./gradlew build --no-daemon --stacktrace

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Upload APK to Google Cloud Storage
        id: upload-apk
        uses: google-github-actions/upload-cloud-storage@v2
        with:
          path: appdir/yetCalc-main/app/build/outputs/apk/debug/app-debug.apk
          destination: android-builder1-deploy/yetCalc-${{ github.sha }}.apk
          public: true

      - name: Set APK URL as environment variable
        run: |
          echo "APK_URL=https://storage.googleapis.com/android-builder1-deploy/yetCalc-${{ github.sha }}.apk" >> $GITHUB_ENV

      - name: Notify webhook
        run: |
          curl -X POST -H "Content-Type: application/json" \
            -d "{\"message\": \"Build completed for yetCalc commit ${{ github.sha }}. APK available at: ${{ env.APK_URL }}\"}" \
            ${{ secrets.WEBHOOK_URL }}
