name: Build Android

on:
  workflow_dispatch:
    inputs:
      zip_url:
        description: "URL to the .zip file (from GCS)"
        required: true
      webhook_url:
        description: "Optional webhook to notify"
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repo
        uses: actions/checkout@v4

      - name: Install required tools
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip openjdk-17-jdk

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Download ZIP from GCS
        run: |
          echo "Downloading ZIP: ${{ github.event.inputs.zip_url }}"
          curl -L -o app.zip "${{ github.event.inputs.zip_url }}"
          unzip -q app.zip -d appdir

      - name: Inject JitPack repository into all build.gradle.kts
        run: |
          find appdir -name "build.gradle.kts" -exec sed -i '/repositories {/a \ \ \ \ maven("https://jitpack.io")' {} +

      - name: List contents
        run: ls -R appdir

      - name: Build Android project
        working-directory: appdir/Simple-Calculator-master
        run: |
          chmod +x ./gradlew || true
          ./gradlew build --no-daemon

      - name: Upload APK(s) as artifact
        uses: actions/upload-artifact@v4
        with:
          name: built-apks
          path: |
            appdir/Simple-Calculator-master/app/build/outputs/apk/**/*.apk

      - name: Notify webhook
        if: github.event.inputs.webhook_url != ''
        run: |
          curl -X POST -H "Content-Type: application/json" \
            -d '{"status": "success", "zip_url": "${{ github.event.inputs.zip_url }}"}' \
            "${{ github.event.inputs.webhook_url }}"

