name: Build yetCalc

on:
  workflow_dispatch:
    inputs:
      zip_url:
        description: "URL to .zip or use checkout"
        required: false
      webhook_url:
        description: "Optional webhook URL"
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip openjdk-17-jdk

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Cache Gradle
        uses: gradle/gradle-build-action@v3
        with:
          cache-name: gradle-cache

      - name: Build Android App
        run: ./gradlew build --no-daemon --stacktrace

      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: yetCalc-apks
          path: |
            app/build/outputs/**/*.apk

      - name: Notify webhook
        if: ${{ github.event.inputs.webhook_url != '' }}
        run: |
          curl -X POST -H "Content-Type: application/json" \
            -d '{"status":"success"}' \
            "${{ github.event.inputs.webhook_url }}"
